pkg/client/cluster.go
spectrocloud/cluster_common.go
spectrocloud/resource_cluster_aws.go
spectrocloud/resource_cluster_azure.go
spectrocloud/resource_cluster_gcp.go
spectrocloud/resource_cluster_import.go
spectrocloud/resource_cluster_vsphere.go

Updating pack changes

---

examples/e2e/eks/README.md
examples/e2e/eks/kubectl.tf
examples/e2e/eks/locals.tf
examples/e2e/eks/outputs.tf
examples/e2e/eks/providers.tf
examples/e2e/eks/resource_cloudaccount.tf
examples/e2e/eks/resource_cluster.tf
examples/e2e/eks/resource_clusterprofile.tf
examples/e2e/eks/terraform.template.tfvars
examples/e2e/eks/variables.tf
go.mod
go.sum
pkg/client/cluster_eks.go
spectrocloud/data_source_cloud_account_aws.go
spectrocloud/provider.go
spectrocloud/resource_cloud_account_aws.go
spectrocloud/resource_cluster_eks.go

Fix eks and e2e eks example

---

examples/e2e/eks/README.md

Updating eks e2e docs

---

examples/e2e/eks/outputs.tf

getting id from created resource

---

examples/e2e/eks/README.md
examples/e2e/eks/resource_cluster.tf
examples/e2e/eks/terraform.template.tfvars
examples/e2e/eks/variables.tf
spectrocloud/resource_cluster_eks.go

eks endpoint access change

---

examples/e2e/eks/resource_cluster.tf

cluster input changes

---

examples/e2e/eks/terraform.template.tfvars
examples/e2e/eks/variables.tf

eks example e2e docs

---

docs/index.md
docs/resources/cluster_eks.md
examples/resources/spectrocloud_cluster_eks/providers.tf
examples/resources/spectrocloud_cluster_eks/resource.tf
examples/resources/spectrocloud_cluster_eks/terraform.template.tfvars
examples/resources/spectrocloud_cluster_eks/variables.tf
examples/resources/spectrocloud_cluster_import/providers.tf
examples/resources/spectrocloud_cluster_import/resource.tf
examples/resources/spectrocloud_cluster_import/terraform.template.tfvars
examples/resources/spectrocloud_cluster_import/variables.tf

@jzhoucliqr, @prathabk, @jgautam Please Review

Adding eks and import examples

---

examples/e2e/eks/resource_cluster.tf
examples/e2e/eks/resource_clusterprofile.tf
examples/e2e/eks/terraform.template.tfvars
examples/e2e/eks/variables.tf
examples/import/gcp/terraform.template.tfvars
examples/import/gcp/variables.tf
examples/import/vsphere/terraform.template.tfvars
examples/import/vsphere/variables.tf
spectrocloud/resource_cluster_aws.go
spectrocloud/resource_cluster_azure.go
spectrocloud/resource_cluster_gcp.go
spectrocloud/resource_cluster_import.go
spectrocloud/resource_cluster_vsphere.go

Import changes

---

spectrocloud/cluster_common.go

@jzhoucliqr, @prathabk, @jgautam Please Review

Scan policy changes

---

docs/resources/project.md
examples/resources/spectrocloud_project/providers.tf
examples/resources/spectrocloud_project/resource.tf
examples/resources/spectrocloud_project/terraform.template.tfvars
examples/resources/spectrocloud_project/variables.tf
pkg/client/project.go
spectrocloud/provider.go
spectrocloud/resource_project.go

Adding project resource

---

docs/data-sources/cloudaccount_openstack.md
docs/resources/cloudaccount_openstack.md
docs/resources/cluster_openstack.md
docs/resources/project.md
examples/e2e/openstack/kubectl.tf
examples/e2e/openstack/locals.tf
examples/e2e/openstack/providers.tf
examples/e2e/openstack/resource_cloudaccount.tf
examples/e2e/openstack/resource_cluster.tf
examples/e2e/openstack/resource_clusterprofile.tf
examples/e2e/openstack/variables.tf
examples/resources/spectrocloud_cloudaccount_openstack/providers.tf
examples/resources/spectrocloud_cloudaccount_openstack/resource.tf
examples/resources/spectrocloud_cloudaccount_openstack/terraform.template.tfvars
examples/resources/spectrocloud_cloudaccount_openstack/variables.tf
examples/resources/spectrocloud_cluster_openstack/providers.tf
examples/resources/spectrocloud_cluster_openstack/resource.tf
examples/resources/spectrocloud_cluster_openstack/terraform.template.tfvars
examples/resources/spectrocloud_cluster_openstack/variables.tf
go.mod
go.sum
pkg/client/cluster_openstack.go
spectrocloud/cluster_common.go
spectrocloud/data_source_cloud_account_openstack.go
spectrocloud/provider.go
spectrocloud/resource_cloud_account_aws.go
spectrocloud/resource_cloud_account_azure.go
spectrocloud/resource_cloud_account_openstack.go
spectrocloud/resource_cluster_openstack.go

added openstack support

---

spectrocloud/resource_team.go

Making users optional field in terraform

---

docs/resources/cluster_aks.md
docs/resources/project.md
examples/resources/spectrocloud_cluster_aks/providers.tf
examples/resources/spectrocloud_cluster_aks/resource.tf
examples/resources/spectrocloud_cluster_aks/terraform.template.tfvars
examples/resources/spectrocloud_cluster_aks/variables.tf
pkg/client/cluster_aks.go
spectrocloud/cluster_common.go
spectrocloud/provider.go
spectrocloud/resource_cluster_aks.go

Aks support

---

docs/data-sources/cluster_profile.md
docs/data-sources/pack.md
docs/resources/team.md
spectrocloud/data_source_cluster_profile.go
spectrocloud/data_source_pack.go

Adding packs in data cluster profile and making registry uid optional

---

spectrocloud/cluster_common.go
spectrocloud/resource_cluster_eks.go

Adding support for overriding manifest layer pack at cluster

---

spectrocloud/data_source_cluster_profile.go
spectrocloud/resource_cluster_profile.go

@jzhoucliqr, @prathabk, @jgautam, @kpiyush17 Please Review

checking manifest content

---

spectrocloud/cluster_common.go
spectrocloud/resource_cluster_eks.go

Adding on-demand as default for eks and aws machines

---

spectrocloud/resource_cluster_aws.go

checking spot instances capacity and max price

---

pkg/client/cluster.go
pkg/client/herr/errors.go
spectrocloud/cluster_common.go
spectrocloud/resource_cluster_aws.go
spectrocloud/resource_cluster_eks.go

@jzhoucliqr, @prathabk, @jgautam, @kpiyush17 Please Review

Adding checks for new api error type

---

spectrocloud/resource_cluster_gcp.go
spectrocloud/resource_cluster_vsphere.go

@saamalik, @nikchern please review

Read cloud config and cache it in state

---

examples/e2e/vsphere/resource_cloudaccount.tf

change description: Code commented in resource_cloudacount.tf file, until we have support for vsphere account

BET-3646: Terraform - Failed to create vsphere cloud account

---

spectrocloud/cluster_common_hash.go
spectrocloud/resource_cluster_libvirt.go

making cpu set optional

---

examples/import/generic/providers.tf
pkg/client/appliance.go
pkg/client/cluster.go
pkg/client/herr/errors.go
spectrocloud/resource_appliance.go
spectrocloud/resource_cluster_import.go

Fixing cluster import and appliance deletion err

---

spectrocloud/cluster_common_fields.go
spectrocloud/cluster_common_host.go
spectrocloud/cluster_common_profiles.go
spectrocloud/provider.go
spectrocloud/resource_cluster_aks.go
spectrocloud/resource_cluster_aws.go
spectrocloud/resource_cluster_azure.go
spectrocloud/resource_cluster_edge.go
spectrocloud/resource_cluster_edge_native.go
spectrocloud/resource_cluster_edge_vsphere.go
spectrocloud/resource_cluster_eks.go
spectrocloud/resource_cluster_gcp.go
spectrocloud/resource_cluster_libvirt.go
spectrocloud/resource_cluster_maas.go
spectrocloud/resource_cluster_nested.go
spectrocloud/resource_cluster_openstack.go
spectrocloud/resource_cluster_tke.go
spectrocloud/resource_cluster_vsphere.go

- also remove `external_ips` support as that field is deprecated until further notice

Fix nested cluster apply/destroy

---

README.md
docs/resources/cluster_profile.md

This PR addresses an issue encountered by users when adding Packs to the cluster profile resource.

docs: cluster profile resournce , multiple packs example

---

examples/resources/spectrocloud_alert/resource.tf
pkg/client/test/alert_test.go
pkg/client/test/utility_test.go
spectrocloud/provider.go
spectrocloud/resource_alert.go

Jira
https://spectrocloud.atlassian.net/browse/PLT-120
Change Description
Unit Test : Implementation for spectrocloud_alerts ( email | http ).
Type of change
[*] Unit Test New feature (non-breaking change which adds functionality) (alerts)
Documentation
https://docs.spectrocloud.com/clusters/cluster-management/health-alerts#overview
Test Results
```
> Credentials & Base config setup completed
-- Test Running with below credentials & base config
* Test host - sivaanand.dev.spectrocloud.com 
* Test email - sivaanand@spectrocloud.com 
* Test pwd - Spectro@1234 
* Test project - Default 
* Test key - **
-------------------------------
=== RUN   TestToAlertEmail
--- PASS: TestToAlertEmail (0.00s)
=== RUN   TestToAlertHttp
0x140004c3ec0
0x1400011cfc0
--- PASS: TestToAlertHttp (0.00s)
=== RUN …
```

Completed Unit test for ToAlert and added err handling in alert read function

---

docs/resources/application_profile.md
examples/resources/spectrocloud_application_profile/providers.tf
examples/resources/spectrocloud_application_profile/resource.tf
examples/resources/spectrocloud_application_profile/terraform.template.tfvars
examples/resources/spectrocloud_application_profile/variables.tf
spectrocloud/resource_application_profile.go
spectrocloud/resource_application_profile_test.go

Jira - https://spectrocloud.atlassian.net/browse/PLT-132
Terraform - Properties field missing for app profile type operator-instance

PLT-132:Added support for properties in application profiles

---

examples/resources/spectrocloud_cluster_aws/resource.tf
spectrocloud/resource_cluster_aws.go
spectrocloud/schemas/cluster_location_config.go

Jira - [PLT-156](https://spectrocloud.atlassian.net/browse/PLT-156)

PLT-156:fixed `azs` day 2 update, capacity_type and location config schema

---

spectrocloud/cluster_common_rbac.go

https://spectrocloud.atlassian.net/browse/PLT-334

PLT-334:Fix for Cluster Role Bindings and Role Bindings

---

examples/resources/spectrocloud_cluster_azure/resource.tf
spectrocloud/resource_cluster_azure.go

JIRA - https://spectrocloud.atlassian.net/browse/PLT-313

PLT-313:Added validation for master node size to accept only odd number

---

examples/e2e/cluster_group/terraform.template.tfvars

Jira - https://spectrocloud.atlassian.net/browse/PLT-348

PLT-348:Removed unused variables from template file

---

examples/resources/spectrocloud_application/providers.tf
examples/resources/spectrocloud_application/terraform.template.tfvars
examples/resources/spectrocloud_application/variables.tf

Jira - https://spectrocloud.atlassian.net/browse/PLT-351

PLT-351:Added template tfvars for spectrocloud_application

---

examples/resources/spectrocloud_cluster_vsphere/resource.tf
spectrocloud/resource_cluster_vsphere.go

PLT-290: Added Validation for cluster, datastore, network and datacenter in day 2 operations

---

spectrocloud/resource_cluster_vsphere.go

PLT-542:Added Validation for resource_pool attribute for control_plane 

---

spectrocloud/resource_cluster_aks.go
spectrocloud/resource_cluster_aws.go
spectrocloud/resource_cluster_azure.go
spectrocloud/resource_cluster_coxedge.go
spectrocloud/resource_cluster_edge_native.go
spectrocloud/resource_cluster_edge_vsphere.go
spectrocloud/resource_cluster_eks.go
spectrocloud/resource_cluster_gcp.go
spectrocloud/resource_cluster_libvirt.go
spectrocloud/resource_cluster_maas.go
spectrocloud/resource_cluster_openstack.go
spectrocloud/resource_cluster_tke.go
spectrocloud/resource_cluster_virtual.go

Jira - 
https://spectrocloud.atlassian.net/browse/PLT-536
Slack Discussion -
https://spectrocloud.slack.com/archives/C03NJBUGH5H/p1687563221872109

PLT-536:Added fix for machine pool type set empty item issue

---

examples/e2e/import/import_block.tf
examples/e2e/import/import_cli.tf

Example for importing cluster profile configuration

PLT-903 Example for importing cluster profile configuration

---

spectrocloud/cluster_common.go

PLT-1282 : Fixed - description field is not getting populated/synced when running cluster import is done

---

spectrocloud/resource_cluster_openstack_test.go
spectrocloud/resource_project_test.go
spectrocloud/resource_team_test.go
spectrocloud/resource_workspace_test.go

test cases written for resource_team, resource_workspace, resource_project & resource_cluster_openstack & tested

test_cases

---

spectrocloud/cluster_common_hash_test.go
spectrocloud/filter_common_test.go

added new unit tests

---

spectrocloud/cluster_common_hash_test.go
spectrocloud/filter_common_test.go
spectrocloud/resource_cluster_attachment_test.go
spectrocloud/resource_cluster_aws_expand_test.go
spectrocloud/resource_cluster_aws_flatten_test.go
spectrocloud/resource_cluster_custom_cloud_test.go

new unit testcases

---

docs/resources/cluster_profile.md
templates/resources/cluster_profile.md.tmpl

This PR adds a documentation example/content that was lost throughout time as the content was not added to the  resource template.
I also added more examples and cleaned up the page.

docs: add missing statement

---

spectrocloud/resource_project.go

Project rename capability
- Tested the rename of the project
- Creation of new project

PLT-1678 Project Rename Capability Using Terraform Provider
